name: bazar_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  market_client:
    git: https://github.com/SlayerOrnstein/market_client.git

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.3.0
