name: market
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  bazar_repository:
    path: packages/bazar_repository
  bloc: ^7.2.1
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  intl: ^0.17.0
  market_client:
    git: https://github.com/SlayerOrnstein/market_client.git
  material_floating_search_bar: ^0.3.4
  path_provider: ^2.0.5
  responsive_builder: ^0.4.1

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  msix: ^2.1.3
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
