name: market
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  market_client:
    git:
      url: https://github.com/SlayerOrnstein/market_client.git
      ref: v1.0.0
  material_floating_search_bar: ^0.3.4
  
dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
