name: market
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  bazar_repository:
    path: packages/bazar_repository
  bloc: ^8.0.2
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.5
  intl: ^0.17.0
  market_client:
    git: https://github.com/SlayerOrnstein/market_client.git
  material_floating_search_bar: ^0.3.6
  path_provider: ^2.0.8
  responsive_builder: ^0.4.1

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  msix: ^2.8.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
